-- Generated by nwg-displays on 2026-07-12 at 14:53:37. Do not edit manually.

hl.monitor({
    output = "HDMI-A-2",
    mode = "1920x1080@239.76",
    position = "5120x238",
    scale = 1.0
})
hl.monitor({
    output = "DP-4",
    mode = "2560x1440@179.95",
    position = "2560x0",
    scale = 1.0
})
hl.monitor({
    output = "DP-5",
    mode = "2560x1440@165.08",
    position = "0x0",
    scale = 1.0
})
